package converter

import (
	"context"
	"encoding/binary"
	"math"
	"os"
	"testing"

	"github.com/svk/wav2mp3/internal/config"
)

// generateSineWAV creates PCM WAV file with sine wave for tests.
func generateSineWAV(t *testing.T, sampleRate, numChannels, bitDepth int, durationSec float64) string {
	t.Helper()
	numSamples := int(float64(sampleRate) * durationSec)
	dataSize := numSamples * numChannels * (bitDepth / 8)

	f, err := os.CreateTemp("", "test_*.wav")
	if err != nil {
		t.Fatal(err)
	}
	name := f.Name()

	// RIFF header
	f.Write([]byte("RIFF"))
	binary.Write(f, binary.LittleEndian, uint32(36+dataSize))
	f.Write([]byte("WAVE"))

	// fmt chunk
	f.Write([]byte("fmt "))
	binary.Write(f, binary.LittleEndian, uint32(16))
	binary.Write(f, binary.LittleEndian, uint16(1)) // PCM
	binary.Write(f, binary.LittleEndian, uint16(numChannels))
	binary.Write(f, binary.LittleEndian, uint32(sampleRate))
	binary.Write(f, binary.LittleEndian, uint32(sampleRate*numChannels*(bitDepth/8)))
	binary.Write(f, binary.LittleEndian, uint16(numChannels*(bitDepth/8)))
	binary.Write(f, binary.LittleEndian, uint16(bitDepth))

	// data chunk
	f.Write([]byte("data"))
	binary.Write(f, binary.LittleEndian, uint32(dataSize))

	const freq = 440.0
	for i := 0; i < numSamples; i++ {
		t_ := float64(i) / float64(sampleRate)
		switch bitDepth {
		case 16:
			s := int16(math.Sin(2*math.Pi*freq*t_) * 32000)
			for ch := 0; ch < numChannels; ch++ {
				binary.Write(f, binary.LittleEndian, s)
			}
		case 8:
			s := uint8(math.Sin(2*math.Pi*freq*t_)*127 + 128)
			for ch := 0; ch < numChannels; ch++ {
				f.Write([]byte{s})
			}
		}
	}
	f.Close()
	return name
}

func TestConvert_Stereo16bit(t *testing.T) {
	wavPath := generateSineWAV(t, 44100, 2, 16, 1.0)
	defer os.Remove(wavPath)

	outPath := wavPath[:len(wavPath)-4] + ".mp3"
	defer os.Remove(outPath)

	opts := config.DefaultConvertOptions()
	opts.InputPath = wavPath
	opts.OutputPath = outPath
	opts.Quiet = true

	stats, err := Convert(context.Background(), opts)
	if err != nil {
		t.Fatalf("conversion failed: %v", err)
	}

	if stats.OutputSizeB == 0 {
		t.Error("output file is empty")
	}

	// Verify file starts with ID3 or MPEG sync
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatal(err)
	}
	if len(data) < 3 {
		t.Fatal("output file too small")
	}

	// Valid headers: ID3 (49 44 33) or MPEG sync (FF FB, FF FA, etc.)
	isID3 := data[0] == 0x49 && data[1] == 0x44 && data[2] == 0x33
	isMPEG := data[0] == 0xFF && (data[1]&0xE0) == 0xE0
	if !isID3 && !isMPEG {
		t.Errorf("output file is not a valid MP3: start %02X %02X %02X", data[0], data[1], data[2])
	}
}

func TestConvert_Mono8bit(t *testing.T) {
	wavPath := generateSineWAV(t, 22050, 1, 8, 0.5)
	defer os.Remove(wavPath)

	outPath := wavPath[:len(wavPath)-4] + ".mp3"
	defer os.Remove(outPath)

	opts := config.DefaultConvertOptions()
	opts.InputPath = wavPath
	opts.OutputPath = outPath
	opts.Quiet = true

	if _, err := Convert(context.Background(), opts); err != nil {
		t.Fatalf("conversion mono 8-bit failed: %v", err)
	}
}

func TestConvert_CBR(t *testing.T) {
	wavPath := generateSineWAV(t, 44100, 2, 16, 0.5)
	defer os.Remove(wavPath)

	outPath := wavPath[:len(wavPath)-4] + ".mp3"
	defer os.Remove(outPath)

	opts := config.ConvertOptions{
		InputPath:  wavPath,
		OutputPath: outPath,
		VBR:        false,
		Bitrate:    128,
		Quality:    5,
		Quiet:      true,
	}

	if _, err := Convert(context.Background(), opts); err != nil {
		t.Fatalf("CBR conversion failed: %v", err)
	}
}

func TestConvert_OutputPathAutoGenerated(t *testing.T) {
	wavPath := generateSineWAV(t, 44100, 2, 16, 0.5)
	defer os.Remove(wavPath)

	// Manually strip WAV extension for predictable name
	expectedMP3 := wavPath[:len(wavPath)-4] + ".mp3"
	defer os.Remove(expectedMP3)

	opts := config.DefaultConvertOptions()
	opts.InputPath = wavPath
	opts.OutputPath = "" // auto
	opts.Quiet = true

	stats, err := Convert(context.Background(), opts)
	if err != nil {
		t.Fatalf("conversion failed: %v", err)
	}
	if stats.OutputPath != expectedMP3 {
		t.Errorf("expected path %s, got %s", expectedMP3, stats.OutputPath)
	}
}

func TestConvert_Stereo24bit(t *testing.T) {
	const fixture = "../../testdata/fixtures/sine_44100_stereo_24.wav"
	if _, err := os.Stat(fixture); os.IsNotExist(err) {
		t.Skip("fixture missing, run: go run testdata/gen_fixtures.go")
	}

	outPath := t.TempDir() + "/out_24bit.mp3"

	opts := config.DefaultConvertOptions()
	opts.InputPath = fixture
	opts.OutputPath = outPath
	opts.Quiet = true

	stats, err := Convert(context.Background(), opts)
	if err != nil {
		t.Fatalf("conversion 24-bit failed: %v", err)
	}
	if stats.WAVInfo.BitDepth != 24 {
		t.Errorf("expected BitDepth=24, got %d", stats.WAVInfo.BitDepth)
	}
	if stats.OutputSizeB == 0 {
		t.Error("output file is empty")
	}
}

func TestConvert_CancelContext(t *testing.T) {
	wavPath := generateSineWAV(t, 44100, 2, 16, 0.5)
	defer os.Remove(wavPath)

	outPath := wavPath[:len(wavPath)-4] + ".mp3"
	defer os.Remove(outPath)

	ctx, cancel := context.WithCancel(context.Background())
	cancel() // immediate cancelation

	opts := config.DefaultConvertOptions()
	opts.InputPath = wavPath
	opts.OutputPath = outPath
	opts.Quiet = true

	_, err := Convert(ctx, opts)
	if err == nil {
		t.Error("expected error on cancelled context")
	}

	// Partial file should be removed
	if _, statErr := os.Stat(outPath); !os.IsNotExist(statErr) {
		t.Error("partial output file should be removed on cancelation")
	}
}
